id: P32DF714D
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Palzang Series
  language: zh
  description: 'Texts by the great Dzogchen master Khenchen Ngawang Palzang (ngag
    dbang dpal bzang, 1879–1941), also known as Khenpo Ngakchung:'
  volume:
    7d53824e411d4e1eb5c071e4a1b0f93a:
      title: Seeds of the Four Philosophical Schools
      parent: Buddhist Philosophy
    ae0b169cc6234e749ba812dc07e36eeb:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    afda2400157442859181301761df2dc0:
      title: The Five Wisdoms
      parent: Dzogchen
    36346736bca644ee8254a36574e19e9d:
      title: Prayer to Pema Tötreng Tsal
      parent: Guru Rinpoche Prayers
    e2f54f754d654771a94958c4678802bb:
      title: Brief Succession of Lives Prayer
      parent: Prayers
    5f554458a6e540d9b10fe60ed3629f6b:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    d8c31d03542549d1a9e5763fc3bf97e0:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
    4b2d137e522e48d89b50b708b08ed444:
      title: Prayer to Khenpo Ngawang Palzang
      parent: Prayers
    053f80ef81e9429fb426880a78450e89:
      title: Brief Homage to the Twenty-One Tārās
      parent: Tārā
created_at: '2022-03-01T00:22:24.760940'
last_modified_at: '2022-03-01T00:22:24.760943'
